todoapp/urls.py
from django.urls import path
from .views import TodoListView, TodoDetailView, TodoCreateView, TodoUpdateView, TodoDeleteView, TodayListView, \
    TodoSearchView, TagFilterView, TagCreateView, TagListView, TagUpdateView, TagDeleteView

app_name = 'todoapp'
urlpatterns = [
    path('', TodoListView.as_view(), name='ListView'),
    path('today', TodayListView.as_view(), name='TodayView'),
    path('<int:pk>', TodoDetailView.as_view(), name='DetailView'),
    path('create/', TodoCreateView.as_view(), name='CreateView'),
    path('update/<int:pk>', TodoUpdateView.as_view(), name='UpdateView'),
    path('delete/<int:pk>', TodoDeleteView.as_view(), name='DeleteView'),
    path('search/', TodoSearchView.as_view(), name='SearchView'),
    path('search/tag=<str:tag>/', TagFilterView.as_view(), name='TagsFilterView'),
    path('tags/create', TagCreateView.as_view(), name='TagCreateView'),
    path('tags/', TagListView.as_view(), name='TagListView'),
    path('tags/update/<int:pk>', TagUpdateView.as_view(), name='TagUpdateView'),
    path('tags/delete/<int:pk>', TagDeleteView.as_view(), name='TagDeleteView'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include(('todoapp.urls', 'todoapp'), namespace='todo')),
]

todoapp/models.py
from colorfield.fields import ColorField
from django.db import models
from django.db.models import Deferrable, UniqueConstraint
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from .choices import TodoPriority, TODO_COLOR_CHOICES


class Tag(models.Model):
    title = models.CharField(_('title'), max_length=40)

    def __str__(self):
        return self.title

    class Meta:
        constraints = [
            UniqueConstraint(name='unique_title', fields=['title'], deferrable=Deferrable.DEFERRED, )
        ]

    def save(self, *args, **kwargs):
        self.title = self.title.replace(' ', '_')
        super(Tag, self).save(*args, **kwargs)


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Todolist(TimeStampMixin):
    title = models.CharField(_('title'), max_length=250, null=False, blank=False)
    description = models.TextField(_('description'), null=False, blank=False)
    priority = models.CharField(_('priority'), max_length=50, choices=TodoPriority.choices, default=TodoPriority.MEDIUM)
    is_done = models.BooleanField(_('is done?'), default=False)
    due_date = models.DateField(_('due date'), default=timezone.now().date())
    color = ColorField(choices=TODO_COLOR_CHOICES, blank=True)
    tags = models.ManyToManyField('Tag')

    @property
    def is_expired(self):
        return self.due_date < timezone.now().date()

    def __str__(self):
        days = (self.due_date - timezone.now().date()).days
        if days == 0:
            return self.title + ' | ' + self.priority.upper() + " | Today"
        if days == -1:
            return self.title + ' | ' + self.priority.upper() + " | Yesterday"
        if days == 1:
            return self.title + ' | ' + self.priority.upper() + " | Tomorrow"
        if days < 0:
            return self.title + ' | ' + self.priority.upper() + " | {0} days ago".format(str(abs(days)))
        else:
            return self.title + ' | ' + self.priority.upper() + " | next {0} days".format(str(days))

    def get_absolute_url(self):
        return reverse('todoapp:ListView')

todoapp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import InlineCheckboxes
from crispy_forms.layout import Submit, Layout, Row, Column, HTML
from .models import Todolist, Tag


class TagCreateFrom(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='form-group  col-md-4 mb-0'),
            ),
        )


class TagUpdateForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='form-group  col-md-4 mb-0'),
            ),
        )


class TodoCreateFrom(forms.ModelForm):
    due_date = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )

    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Todolist
        fields = ['title', 'description', 'priority', 'due_date', 'tags', 'is_done', 'color']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.layout = Layout(

            Row(
                Column('title', css_class='form-group  col-md-4 mb-0'),
                Column('priority', css_class='form-group col-md-4 mb-0'),
                Column('due_date', css_class='form-group col-md-4 mb-0'),

            ),
            Row(
                Column('description', css_class='form-group  col-md-8 mb-0'),
                Column('color', css_class='form-group col-md-4 mb-0 '),
            ),
            'is_done',
            InlineCheckboxes(
                'tags', ''
            ),
        )

todoapp/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TodayArchiveView
from .models import Todolist, Tag
from django.urls import reverse_lazy
from .forms import TodoCreateFrom, TagUpdateForm, TagCreateFrom


class TodoListView(ListView):
    model = Todolist
    paginate_by = 8
    template_name = 'todoapp/todo_list_view.html'


class TagFilterView(ListView):
    def get_context_data(self, **kwargs):
        context = super(TagFilterView, self).get_context_data(**kwargs)
        context.update({
            'tags': Tag.objects.all(),
        })
        return context

    def get_queryset(self):
        query_list = self.model.objects.filter(tags__title__icontains=self.kwargs['tag']).order_by('-id')
        return query_list

    paginate_by = 2
    model = Todolist
    template_name = 'todoapp/todo_search_view.html'


class TagCreateView(CreateView):
    model = Tag
    form_class = TagCreateFrom
    template_name = 'todoapp/tag_create_view.html'
    success_url = reverse_lazy('todoapp:TagListView')


class TagListView(ListView):
    model = Tag
    paginate_by = 50
    template_name = 'todoapp/tag_list_view.html'
    context_object_name = 'tags'

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        related_tasks = {}
        tasks = []
        """Create a dictionary named related_tasks which it's keys are the tag ids and the values are 
        the title of tasks of the related tag.
        example:  related_tasks = {'tag1':['task1', 'task2'], 'tag2:['task1', 'task3', 'task5']}"""
        for tag in Tag.objects.all():
            for task in tag.todolist_set.all():
                tasks.append(task.title)
            related_tasks[tag.id] = tasks
            tasks = []
        context.update({
            'related_tasks': related_tasks,
        })
        return context


class TagUpdateView(UpdateView):
    model = Tag
    form_class = TagUpdateForm
    template_name = 'todoapp/tag_update_view.html'
    success_url = reverse_lazy('todoapp:TagListView')


class TagDeleteView(DeleteView):
    model = Tag
    template_name = 'todoapp/tag_delete_view.html'
    success_url = reverse_lazy('todoapp:TagListView')


class TodoSearchView(ListView):

    def get_context_data(self, **kwargs):
        context = super(TodoSearchView, self).get_context_data(**kwargs)
        context.update({
            'tags': Tag.objects.all(),
        })
        return context

    def get_queryset(self):
        query_list = self.model.objects.all()
        query = self.request.GET.get('search')
        if query:
            query_list = self.model.objects.filter(title__icontains=query).order_by('-id')
        return query_list

    paginate_by = 2
    model = Todolist
    template_name = 'todoapp/todo_search_view.html'


class TodayListView(TodayArchiveView):
    model = Todolist
    paginate_by = 2
    date_field = 'created_at'
    template_name = 'todoapp/today_list_view.html'


class TodoDetailView(DetailView):
    model = Todolist
    template_name = 'todoapp/todo_detail_view.html'


class TodoCreateView(CreateView):
    model = Todolist
    form_class = TodoCreateFrom
    template_name = 'todoapp/todo_create_view.html'


class TodoUpdateView(UpdateView):
    model = Todolist
    form_class = TodoCreateFrom
    template_name = 'todoapp/todo_update_view.html'


class TodoDeleteView(DeleteView):
    model = Todolist
    success_url = reverse_lazy('todoapp:ListView')
    template_name = 'todoapp/todo_delete_view.html'

todoapp/templates/todoapp/base.html
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"#}
    {#          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">#}

    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>#}
    {#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>#}
    {#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"#}
    {#            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"#}
    {#            crossorigin="anonymous"></script>#}
    {#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"#}
    {#            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"#}
    {#            crossorigin="anonymous"></script>#}
    {#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"#}
    {#            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"#}
    {#            crossorigin="anonymous"></script>#}
    {##}
    {##}
    {##}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">


    <a class="navbar-brand" href="#">Todo</a>

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todoapp:ListView' %}">List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todoapp:CreateView' %}">Add</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todoapp:TodayView' %}">Today</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todoapp:SearchView' %}">Search</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Done</a>
        </li>
        <!-- Dropdown -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Tags
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'todoapp:TagListView' %}">Tags List</a>
                <a class="dropdown-item" href="{% url 'todoapp:TagCreateView' %}">Create Tag</a>
            </div>
        </li>
    </ul>
    {% block nav %}
    {% endblock %}

</nav>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Todo App</h1>
            <hr class="mt-0 mb-4">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer class="text-center text-white" style="background-color: #f1f1f1;">
        <div class="container pt-4">
            <section class="mb-4">
                <a
                        class="btn btn-link btn-floating btn-lg text-dark m-1"
                        href="https://twitter.com/thatsmostafa"
                        role="button"
                        data-mdb-ripple-color="dark"
                ><i class="fab fa-twitter"></i
                ></a>
                <a
                        class="btn btn-link btn-floating btn-lg text-dark m-1"
                        href="mailto:mostafa.programming@gmail.com"
                        role="button"
                        data-mdb-ripple-color="dark"
                ><i class="fab fa-google"></i
                ></a>
                <a
                        class="btn btn-link btn-floating btn-lg text-dark m-1"
                        href="https://instagram.com/mostafa.abdi2019"
                        role="button"
                        data-mdb-ripple-color="dark"
                ><i class="fab fa-instagram"></i
                ></a>
                <a
                        class="btn btn-link btn-floating btn-lg text-dark m-1"
                        href="https://www.linkedin.com/in/mostafa-a-b62337117/"
                        role="button"
                        data-mdb-ripple-color="dark"
                ><i class="fab fa-linkedin"></i
                ></a>
                <a
                        class="btn btn-link btn-floating btn-lg text-dark m-1"
                        href="https://gitlab.com/mostafaabdi/"
                        role="button"
                        data-mdb-ripple-color="dark"
                ><i class="fab fa-gitlab"></i
                ></a>
            </section>
        </div>
        <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2021 Copyright:
            <a class="text-dark" href="https://mostafaabdi.com/">mostafaabdi.com</a>
        </div>
    </footer>
</div>
</body>
</html>

todoapp/templates/todoapp/tag_create_view.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Add New Tag</h2>
    {% csrf_token %}
    {% crispy form %}
{% endblock %}

todoapp/templates/todoapp/tag_delete_view.html
{% extends 'todoapp/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

todoapp/templates/todoapp/tag_list_view.html
{% extends 'todoapp/base.html' %}
{% load filters %}
{% block content %}

    <h2>List of your tags</h2>
    <ul>

        <table class="table table-light table-hover overflow-auto">
            <thead>
            <tr>
                <th>Title</th>
                <th>Related Tasks</th>
            </tr>
            </thead>
            <tbody>
            <input class="form-control" id="myInput" type="text" placeholder="Search..">
            {% for tag in tags %}
                <tr id="myTable">
                    <td>
                        <a href="{% url 'todoapp:TagUpdateView' tag.id %}" data-toggle="tooltip"
                           title="click to edit tag">#{{ tag }}</a>
                    </td>
                    <td>
                        {% for i in  related_tasks|get_value_from_dict:tag.id %}
                           [ {{ i }} ]
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </ul>


    {#   start script for tooltip#}
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
    {#   end script for tooltip#}


    {#   start script for filter#}
    <script>
        $(document).ready(function () {
            $("#myInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable td").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
    {#   end script for filter#}

    {#    pagination#}
    {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            {% endif %}
        </ul>
    {% endif %}
    {#    end pagination#}
{% endblock %}

todoapp/templates/todoapp/tag_update_view.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Update tag: {{ object }}</h2>
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
    <a href="{% url 'todoapp:TagDeleteView' object.id %}"><button class="btn btn-danger">Delete</button></a>
{% endblock %}

todoapp/templates/todoapp/today_list_view.html
{% extends 'todoapp/base.html' %}
{% block nav %}
{% endblock %}
{% block content %}
    <div class="container">
        <h2>Today todo list</h2>
        <ul>
            {% for todo in page_obj %}
                <div class="container">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-header">
                                {% if todo.is_done %}
                                    <div class="bg-success">
                                        done: Yes
                                    </div>
                                {% else %}
                                    <div class="bg-warning">
                                        done: No
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                title: <a href="{% url 'todoapp:DetailView' todo.id %}">{{ todo.title }}</a>
                            </div>
                            <div class="card-text">
                                description: {{ todo.description }}
                            </div>
                            <div class="card-footer">
                                due date: {{ todo.due_date }}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </ul>
        {% if page_obj.has_other_pages %}
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link"
                                                 href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

todoapp/templates/todoapp/todo_create_view.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Add New Task</h2>
    {% csrf_token %}
    {% crispy form %}
{% endblock %}

todoapp/templates/todoapp/todo_delete_view.html
{% extends 'todoapp/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

todoapp/templates/todoapp/todo_detail_view.html
{% extends 'todoapp/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;"><h1>{{ object.title }}</h1></div>
        </div>
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;">description: {{ object.description }}</div>
        </div>
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;">priority: {{ object.priority }}</div>
        </div>
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;">done: {{ object.is_done }}</div>
        </div>
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;">due date: {{ object.due_date }}</div>
        </div>
        <div class="row">
            <div style="background-color:{{ object.color }};width: 2.33%"></div>
            <div class="col" style="background-color:lavender;">tags:{% for tag in object.tags.all %}
                <a class=" badge badge-primary" href="{% url 'todoapp:TagsFilterView' tag %}">
                    #{{ tag }}
                </a>
                &nbsp;{% endfor %}
            </div>
        </div>
        <a href="{% url 'todoapp:UpdateView' object.id %}"><span class="badge badge-warning">Update Item</span></a>
        <a href="{% url 'todoapp:DeleteView' object.id %}"><span class="badge badge-danger">Delete Item</span></a>
    </div>
{% endblock %}

todoapp/templates/todoapp/todo_list_view.html
{% extends 'todoapp/base.html' %}
{% block content %}
    <h2>List of your todo</h2>
    <ul>
        <table class="table table-light table-hover overflow-auto">
            <thead>
            <tr>
                <th>title</th>
                <th>description</th>
                <th>due date</th>
                <th style="width: 1.33%;"></th>
            </tr>
            </thead>
            <tbody>
            {% for todo in object_list %}
                <tr>
                    {% if todo.is_done %}
                        <td>
                            <del><a href="{% url 'todoapp:DetailView' todo.id %}">{{ todo.title }}</a></del>
                        </td>
                    {% else %}
                        <td><a href="{% url 'todoapp:DetailView' todo.id %}">{{ todo.title }}</a></td>
                    {% endif %}
                    {% if todo.is_done %}
                        <td>
                            <del>{{ todo.description }}</del>
                        </td>
                    {% else %}
                        <td>{{ todo.description }}</td>
                    {% endif %}
                    {% if todo.is_expired and not todo.is_done%}
                        <td style="color: red">{{ todo.due_date }}</td>
                    {% else %}
                        <td>{{ todo.due_date }}</td>
                    {% endif %}
                    <td style="background-color:{{ todo.color }};width: 1.33%;"></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </ul>

{#    pagination#}
    {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            {% endif %}
        </ul>
    {% endif %}
{#    end pagination#}
{% endblock %}

todoapp/templates/todoapp/todo_search_view.html
{% extends 'todoapp/base.html' %}
{% block content %}
    <h2>Search In Tasks</h2>
    <form method="GET">
        {% csrf_token %}
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="search" placeholder="Search">
            <div class="input-group-append">
                <button class="btn btn-success" type="submit">Go</button>
            </div>
        </div>
    </form>
    {% if tags %}
        {% for tag in tags %}
            <a href="{% url 'todoapp:TagsFilterView' tag%}"><div class=" badge badge-primary">#{{ tag }}</div></a>
        {% endfor %}
    {% endif %}
    <ul>
        {% for todo in page_obj %}
            <div class="container">
                <div class="card">
                    <div class="card-header">
                        <div class="card-header">
                            {% if todo.is_done %}
                                <div class="bg-success">
                                    done: Yes
                                </div>
                            {% else %}
                                <div class="bg-warning">
                                    done: No
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-title">
                            title: <a href="{% url 'todoapp:DetailView' todo.id %}">{{ todo.title }}</a>
                        </div>
                        <div class="card-text">
                            description: {{ todo.description }}
                        </div>
                        <div class="card-footer">
                            {% if todo.is_expired and not todo.is_done %}
                                <div style="color: red"> due date: {{ todo.due_date }}</div>
                            {% else %}
                                due date: {{ todo.due_date }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </ul>
    {#    pagination#}
    {% if page_obj.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link"
                                         href="?search={{ request.GET.search }}&page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active"><a class="page-link" href="#">{{ i }} </a></li>
                {% else %}
                    <li class="page-item"><a class="page-link"
                                             href="?search={{ request.GET.search }}&page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?search={{ request.GET.search }}&page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            {% endif %}
        </ul>
    {% endif %}
    {#    end of pagination#}
{% endblock %}

todoapp/templates/todoapp/todo_update_view.html
{% extends 'todoapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}